name: Auto Tag & Publish Python Package 🐍

on:
  push:
    branches:
      - main

jobs:
  bump-tag-build-publish:
    name: Bump, tag, build, and publish
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for bump2version and tagging

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install build bump2version

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        run: |
          bump2version patch
          git push origin main --tags

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
